  export default [
    { name:'bulbasur' , img:'/docs/assets/images/bulbasaur.png'},
    { name:'butterfree' , img:'/docs/assets/images/butterfree.png'},
    { name:'caterpie' , img:'/docs/assets/images/caterpie.png'},
    { name:'chansey' , img:'/docs/assets/images/chansey.png'},
    { name:'charizard' , img:'/docs/assets/images/charizard.png'},
    { name:'charmander' , img:'/docs/assets/images/charmander.png'},
    { name:'charmeleon' , img:'/docs/assets/images/charmeleon.png'},
    { name:'clefairy' , img:'/docs/assets/images/clefairy.png'},
    { name:'cloyster' , img:'/docs/assets/images/cloyster.png'},
    { name:'cubone' , img:'/docs/assets/images/cubone.png'},
     { name:'dewgong' , img:'/docs/assets/images/dewgong.png'},
    { name:'diglett' , img:'/docs/assets/images/diglett.png'},
    { name:'bulbasur' , img:'/docs/assets/images/bulbasaur.png'},
    { name:'butterfree' , img:'/docs/assets/images/butterfree.png'},
    { name:'caterpie' , img:'/docs/assets/images/caterpie.png'},
    { name:'chansey' , img:'/docs/assets/images/chansey.png'},
    { name:'charizard' , img:'/docs/assets/images/charizard.png'},
    { name:'charmander' , img:'/docs/assets/images/charmander.png'},
    { name:'charmeleon' , img:'/docs/assets/images/charmeleon.png'},
    { name:'clefairy' , img:'/docs/assets/images/clefairy.png'},
    { name:'cloyster' , img:'/docs/assets/images/cloyster.png'},
    { name:'cubone' , img:'/docs/assets/images/cubone.png'},
     { name:'dewgong' , img:'/docs/assets/images/dewgong.png'},
    { name:'diglett', img:'/docs/assets/images/diglett.png'},
    {name:'ditto' , img:'/docs/assets/images/ditto.png'},
    { name:'dodrio-f' , img:'/docs/assets/images/dodrio-f.png'},
    { name:'doduo-f' , img:'/docs/assets/images/doduo-f.png'},
    { name:'doduo' , img:'/docs/assets/images/doduo.png'},
    { name:'dragonair' , img:'/docs/assets/images/dragonair.png'},
    { name:'dragonite' , img:'/docs/assets/images/dragonite.png'},
    { name:'dratini' , img:'/docs/assets/images/dratini.png'},
    { name:'drowzee' , img:'/docs/assets/images/drowzee.png'},
    { name:'dugtrio' , img:'/docs/assets/images/dugtrio.png'},
    { name:'eevee' , img:'/docs/assets/images/eevee.png'},
    { name:'ekans' , img:'/docs/assets/images/ekans.png'},
    { name:'electabuzz' , img:'/docs/assets/images/electabuzz.png'},
    { name:'electrode' , img:'/docs/assets/images/electrode.png'},
    { name:'exeggcute' , img:'/docs/assets/images/exeggcute.png'},
    { name:'exeggutor' , img:'/docs/assets/images/exeggutor.png'},
    { name:'farfetchd' , img:'/docs/assets/images/farfetchd.png'},
    { name:'fearow' , img:'/docs/assets/images/fearow.png'},
    { name:'flareon' , img:'/docs/assets/images/flareon.png'},
    { name:'gastly' , img:'/docs/assets/images/gastly.png'},
    { name:'gengar' , img:'/docs/assets/images/gengar.png'},
    { name:'geodude' , img:'/docs/assets/images/geodude.png'},
    { name:'gloom-f' , img:'/docs/assets/images/gloom-f.png'},
    { name:'golbat-f' , img:'/docs/assets/images/golbat-f.png'},
    { name:'goldeen' , img:'/docs/assets/images/goldeen.png'},
    { name:'golduck' , img:'/docs/assets/images/golduck.png'},
    { name:'golem' , img:'/docs/assets/images/golem.png'},
    { name:'graveler' , img:'/docs/assets/images/graveler.png'},
    { name:'grimer' , img:'/docs/assets/images/grimer.png'},
    { name:'growlithe' , img:'/docs/assets/images/growlithe.png'},
    { name:'gyarados' , img:'/docs/assets/images/gyarados.png'},
    { name:'haunter' , img:'/docs/assets/images/haunter.png'},
    { name:'hitmonchan' , img:'/docs/assets/images/hitmonchan.png'},
    { name:'hitmonlee' , img:'/docs/assets/images/hitmonlee.png'},
    { name:'horsea' , img:'/docs/assets/images/horsea.png'},
    { name:'hypno-f' , img:'/docs/assets/images/hypno-f.png'},
    { name:'ivysaur' , img:'/docs/assets/images/ivysaur.png'},
    { name:'jigglypuff' , img:'/docs/assets/images/jigglypuff.png'},
    { name:'jolteon' , img:'/docs/assets/images/jolteon.png'},
    { name:'jynx' , img:'/docs/assets/images/jynx.png'},
    { name:'kabuto' , img:'/docs/assets/images/kabuto.png'},
    { name:'kabutops' , img:'/docs/assets/images/kabutops.png'},
    { name:'kadabra-f' , img:'/docs/assets/images/kadabra-f.png'},
    { name:'kakuna' , img:'/docs/assets/images/kakuna.png'},
    { name:'kangaskhan' , img:'/docs/assets/images/kangaskhan.png'},
    { name:'kingler' , img:'/docs/assets/images/kingler.png'},
    { name:'koffing' , img:'/docs/assets/images/koffing.png'},
    { name:'krabby' , img:'/docs/assets/images/krabby.png'},
    { name:'lapras' , img:'/docs/assets/images/lapras.png'},
    { name:'lickitung' , img:'/docs/assets/images/lickitung.png'},
    { name:'machamp' , img:'/docs/assets/images/machamp.png'},
    { name:'machoke' , img:'/docs/assets/images/machoke.png'},
    { name:'machop' , img:'/docs/assets/images/machop.png'},
    { name:'magikarp-f' , img:'/docs/assets/images/magikarp-f.png'},
    { name:'magmar' , img:'/docs/assets/images/magmar.png'},
    { name:'magnemite' , img:'/docs/assets/images/magnemite.png'},
    { name:'magneton' , img:'/docs/assets/images/magneton.png'},
    { name:'mankey' , img:'/docs/assets/images/mankey.png'},
    { name:'marowak' , img:'/docs/assets/images/marowak.png'},
    { name:'meowth' , img:'/docs/assets/images/meowth.png'},
    { name:'metapod' , img:'/docs/assets/images/metapod.png'},
    { name:'mew' , img:'/docs/assets/images/mew.png'},
    { name:'mewtwo' , img:'/docs/assets/images/mewtwo.png'},
    { name:'moltres' , img:'/docs/assets/images/moltres.png'},
    { name:'mr-mime' , img:'/docs/assets/images/mr-mime.png'},
    { name:'muk' , img:'/docs/assets/images/muk.png'},
    { name:'nidoqueen' , img:'/docs/assets/images/nidoqueen.png'},
    { name:'nidoran-f' , img:'/docs/assets/images/nidoran-f.png'},
    { name:'nidorina' , img:'/docs/assets/images/nidorina.png'},
    { name:'nidorino' , img:'/docs/assets/images/nidorino.png'},
    { name:'ninetales' , img:'/docs/assets/images/ninetales.png'},
    { name:'oddish' , img:'/docs/assets/images/oddish.png'},
    { name:'omanyte' , img:'/docs/assets/images/omanyte.png'},
    { name:'omastar' , img:'/docs/assets/images/omastar.png'},
    { name:'onix' , img:'/docs/assets/images/onix.png'},
    { name:'paras' , img:'/docs/assets/images/paras.png'},
    { name:'parasect' , img:'/docs/assets/images/parasect.png'},
    { name:'persian' , img:'/docs/assets/images/persian.png'},
    { name:'pidgeot' , img:'/docs/assets/images/pidgeot.png'},
    { name:'pidgeotto' , img:'/docs/assets/images/pidgeotto.png'},
    { name:'pidgey' , img:'/docs/assets/images/pidgey.png'},
    { name:'pikachu' , img:'/docs/assets/images/pikachu.png'},
    { name:'pinsir' , img:'/docs/assets/images/pinsir.png'},
    { name:'poliwag' , img:'/docs/assets/images/poliwag.png'},
    { name:'poliwhirl' , img:'/docs/assets/images/poliwhirl.png'},
    { name:'ponyta' , img:'/docs/assets/images/ponyta.png'},
    { name:'porygon' , img:'/docs/assets/images/porygon.png'},
    { name:'primeape' , img:'/docs/assets/images/primeape.png'},
    { name:'psyduck' , img:'/docs/assets/images/psyduck.png'},
    { name:'raichu' , img:'/docs/assets/images/raichu.png'},
    { name:'rapidash' , img:'/docs/assets/images/rapidash.png'},
    { name:'raticate' , img:'/docs/assets/images/raticate.png'},
    { name:'rattata' , img:'/docs/assets/images/rattata.png'},
    { name:'rhydon-f' , img:'/docs/assets/images/rhydon-f.png'},
    { name:'rhyhorn-f' , img:'/docs/assets/images/rhyhorn-f.png'},
    { name:'sandshrew' , img:'/docs/assets/images/sandshrew.png'},
    { name:'sandslash' , img:'/docs/assets/images/sandslash.png'},
    { name:'scyther-f' , img:'/docs/assets/images/scyther-f.png'},
    { name:'seadra' , img:'/docs/assets/images/seadra.png'},
    { name:'seaking-f' , img:'/docs/assets/images/seaking-f.png'},
    { name:'seel' , img:'/docs/assets/images/seel.png'},
    { name:'shellder' , img:'/docs/assets/images/shellder.png'},
    { name:'slowbro' , img:'/docs/assets/images/slowbro.png'},
    { name:'slowpoke' , img:'/docs/assets/images/slowpoke.png'},
    { name:'snorlax' , img:'/docs/assets/images/snorlax.png'},
    { name:'spearow' , img:'/docs/assets/images/spearow.png'},
    { name:'squirtle' , img:'/docs/assets/images/squirtle.png'},
    { name:'starmie' , img:'/docs/assets/images/starmie.png'},
    { name:'staryu' , img:'/docs/assets/images/staryu.png'},
    { name:'tangela' , img:'/docs/assets/images/tangela.png'},
    { name:'tauros' , img:'/docs/assets/images/tauros.png'},
    { name:'tentacool' , img:'/docs/assets/images/tentacool.png'},
    { name:'tentacruel' , img:'/docs/assets/images/tentacruel.png'},
    { name:'vaporeon' , img:'/docs/assets/images/vaporeon.png'},
    { name:'venomoth' , img:'/docs/assets/images/venomoth.png'},
    { name:'venonat' , img:'/docs/assets/images/venonat.png'},
    { name:'venusaur' , img:'/docs/assets/images/venusaur.png'},
    { name:'victreebel' , img:'/docs/assets/images/victreebel.png'},
    { name:'vileplume' , img:'/docs/assets/images/vileplume.png'},
    { name:'voltorb' , img:'/docs/assets/images/voltorb.png'},
    { name:'vulpix' , img:'/docs/assets/images/vulpix.png'},
    { name:'wartortle' , img:'/docs/assets/images/wartortle.png'},
    { name:'weedle' , img:'/docs/assets/images/weedle.png'},
    { name:'weepinbell' , img:'/docs/assets/images/weepinbell.png'},
    { name:'weezing' , img:'/docs/assets/images/weezing.png'},
    { name:'wigglytuff' , img:'/docs/assets/images/wigglytuff.png'},
    { name:'zapdos' , img:'/docs/assets/images/zapdos.png'},
    { name:'zubat-f' , img:'/docs/assets/images/zubat-f.png'},
  ];  

 /*  const cards = [
    { name: 'bulbasur', img: '/docs/assets/images/bulbasaur.png' },
    { name: 'butterfree', img: '/docs/assets/images/butterfree.png' },
    { name: 'caterpie', img: '/docs/assets/images/caterpie.png' },
    { name: 'chansey', img: '/docs/assets/images/chansey.png' },
    { name: 'charizard', img: '/docs/assets/images/charizard.png' },
    { name: 'charmander', img: '/docs/assets/images/charmander.png' },
    { name: 'charmeleon', img: '/docs/assets/images/charmeleon.png' },
    { name: 'clefairy', img: '/docs/assets/images/clefairy.png' },
    { name: 'cloyster', img: '/docs/assets/images/cloyster.png' },
    { name: 'cubone', img: '/docs/assets/images/cubone.png' },
    { name: 'dewgong', img: '/docs/assets/images/dewgong.png' },
    { name: 'diglett', img: '/docs/assets/images/diglett.png' },
    { name: 'bulbasur', img: '/docs/assets/images/bulbasaur.png' },
    { name: 'butterfree', img: '/docs/assets/images/butterfree.png' },
    { name: 'caterpie', img: '/docs/assets/images/caterpie.png' },
    { name: 'chansey', img: '/docs/assets/images/chansey.png' },
    { name: 'charizard', img: '/docs/assets/images/charizard.png' },
    { name: 'charmander', img: '/docs/assets/images/charmander.png' },
    { name: 'charmeleon', img: '/docs/assets/images/charmeleon.png' },
    { name: 'clefairy', img: '/docs/assets/images/clefairy.png' },
    { name: 'cloyster', img: '/docs/assets/images/cloyster.png' },
    { name: 'cubone', img: '/docs/assets/images/cubone.png' },
    { name: 'dewgong', img: '/docs/assets/images/dewgong.png' },
    { name: 'diglett', img: '/docs/assets/images/diglett.png' },
  ];

  cards.forEach((card)=>{
    console.log(Math.floor(Math.random(card.img)));

  }); */