export default [
    { name: 'bulbasur', img: '/images/bulbasaur.png' },
    { name: 'butterfree', img: '/images/butterfree.png' },
    { name: 'caterpie', img: '/images/caterpie.png' },
    { name: 'chansey', img: '/images/chansey.png' },
    { name: 'charizard', img: '/images/charizard.png' },
    { name: 'charmander', img: '/images/charmander.png' },
    { name: 'charmeleon', img: '/images/charmeleon.png' },
    { name: 'clefairy', img: '/images/clefairy.png' },
    { name: 'cloyster', img: '/images/cloyster.png' },
    { name: 'cubone', img: '/images/cubone.png' },
    { name: 'dewgong', img: '/images/dewgong.png' },
    { name: 'diglett', img: '/images/diglett.png' },
    { name: 'bulbasur', img: '/images/bulbasaur.png' },
    { name: 'butterfree', img: '/images/butterfree.png' },
    { name: 'caterpie', img: '/images/caterpie.png' },
    { name: 'chansey', img: '/images/chansey.png' },
    { name: 'charizard', img: '/images/charizard.png' },
    { name: 'charmander', img: '/images/charmander.png' },
    { name: 'charmeleon', img: '/images/charmeleon.png' },
    { name: 'clefairy', img: '/images/clefairy.png' },
    { name: 'cloyster', img: '/images/cloyster.png' },
    { name: 'cubone', img: '/images/cubone.png' },
    { name: 'dewgong', img: '/images/dewgong.png' },
    { name: 'diglett', img: '/images/diglett.png' },
  ];